FROM node:18

WORKDIR /usr/src/servicio-cuotas

COPY package*.json ./
RUN npm install

# No necesitamos copiar los archivos ni hacer build aquí
# ya que usaremos bind mount en desarrollo
# COPY . .


EXPOSE ${CUOTAS_PORT} 
CMD ["npm", "run", "start:dev"]
