FROM node:18

WORKDIR /usr/src/frontend

# Instala Angular CLI globalmente para desarrollo
RUN npm install -g @angular/cli

# Copia solo los archivos de configuración necesarios para instalar dependencias
COPY package.json package-lock.json ./

# Instala dependencias (esto se ejecutará una sola vez en el contenedor)
RUN npm install

EXPOSE ${FRONT_PORT} 

# Esto funciona solo por que pasaste el .env al contenedor, desde el compose.

CMD ["npm", "start"]

## No se copia todo por el bind mount, y tener en cuenta que en el futuro para deployar recomiendan armar otra imagen distinta, con otro "SO"