FROM node:20-alpine

WORKDIR /usr/src/frontend

RUN npm install -g @angular/cli 

COPY package*.json ./

RUN npm install

EXPOSE ${FRONT_PORT} 

CMD sh -c "ng serve --host 0.0.0.0 --port ${ANGULAR_PORT}"

# Es necesario el --host 0.0.0.0 para que el servidor donde corre Angular dentro del contenedor
# escuche peticiones provenientes desde fuera del contenedor. 