### Subir user

POST http://localhost:3000/api/users/user
Content-Type: application/json

{
    "email": "agosMonti@hotmail.com",
    "password": "password123",
    "socio":3

}

### Subir admin

POST http://localhost:3000/api/auth/admin
Content-Type: application/json

{
    "email": "admin2@hotmail.com",
    "password": "admin123"

}

### Subir user

POST http://localhost:3000/api/users/user
Content-Type: application/json

{
    "email": "agosMonti3@hotmail.com",
    "password": "password123",
    "socio":5

}