
### Obtener todos los libros
GET http://localhost:3000/api/libros/

### Subir libro

POST http://localhost:3000/api/libros
Content-Type: application/json

{
    "titulo": "Don quijote",
    "descripcion": "Un clásico de la literatura contemporanéa",
    "isbn": "0-545-01022-5",
    "miAutor": 1,      
    "miEditorial": 1,
    "cantEjemplares": 2

}

### Delete de un libro por ID

DELETE  http://localhost:3000/api/libros/2




### Actualizar autor con PUT
PUT http://localhost:3000/api/libros/1
Content-Type: application/json

{
    "titulo":"Moby Dick",
    "descripcion": "Un clásico de la literatura contemporanéa. Aclamado por la crítica internacional",
    "isbn": "0-7645-2641-3",
    "miAutor": 1,
    "miEditorial": 1

}

### Actualizar autor con PATCH
PATCH http://localhost:3000/api/libros/16
Content-Type: application/json

{
    "titulo": "Libro PATCHEEE"

}

### Get primera página
GET  http://localhost:3000/api/libros/byPage?pageIndex=0&pageSize=5&sortColumn=id&sortOrder=asc&filterValue=