


### Get primera página
GET  http://localhost:3000/api/prestamos?pageIndex=0&pageSize=5&sortColumn=fechaPrestamo&sortOrder=asc&filterValue=

### Get one
GET  http://localhost:3000/api/prestamos/1/detail