FROM node:20 
# Verificar que funcione, antes tenia 18.

WORKDIR /usr/src/api

COPY package*.json ./
RUN npm install

# No necesitamos copiar los archivos ni hacer build aquí
# ya que usaremos bind mount en desarrollo
# COPY . .


EXPOSE ${API_PORT} 
CMD ["npm", "run", "start:dev"]
