FROM node:20-alpine
WORKDIR /usr/src/frontend
RUN npm install -g @angular/cli
COPY package*.json ./
RUN npm install
COPY . .
RUN ng build --configuration production
EXPOSE 80
CMD ["npx", "serve", "-s", "dist/nombre-de-tu-app", "-l", "80"]